### ISSUE TITLE
How to call : captureStillImageAsynchronouslyFromConnection using ur framework ?

### ISSUE THREAD

**Issue by anitalanet** [mcgraw/dojo-custom-camera#6]
Hi there..

I am using your framework for custom camera..

Now i have the requirement for the capturing multiple image as single shot (burst mode) .. and i came to know that  "captureStillImageAsynchronouslyFromConnection" this method is used for the capturing multiple images now how can i call this for capturing multiple images as burst mode.. ?

Can anyone help me in that for solution

A great help is appricaiated

Thanks in andvance

**Comment by mcgraw** [comment]
You could call captureStillImageAsynchronouslyFromConnection multiple times in order to capture shots, but I imagine you're going to run into some difficulties there. It might be a worthwhile exercise to experiment with so you can see what happens.

I would also point you to the video aspects of AVFoundation. Start recording, save frame data, stop recording. 

Word of caution. This is just a basic example that followed a tutorial I wrote. It's not meant to act as a dedicated library. You might find something far better browsing https://github.com/vsouza/awesome-ios

**Comment by anitalanet** [comment]
Hey mcgraw.. thanks for your answer and time. Yesterday i tried with other efforts but if i am capable of capturing multiple images as single shot...but how can i save them as burst image in library.. because i need to access the burst type images also from mah gallery ? i am not getting any solution for that...

**Comment by mcgraw** [comment]
Unfortunately that capability is not publicly exposed so you'll need to let your app handle that sort of behavior (capture x frames, only show one frame while allowing a user to tap into it).

The best way to discover capability is to reference the documentation. You've got AVFoundation, which is responsible for capturing image and video data (not saving to disk). Saving to disk is handled by UIKit. Here is one of the methods (with no indication of anything "burst" related), for example:

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/#//apple_ref/c/func/UIImageWriteToSavedPhotosAlbum
